services:
    laravel.test:
        build:
          context: .
          dockerfile: docker/app/Dockerfile
        command: /usr/sbin/php-fpm82 -F
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER:-1000}'
            WWWGROUP: '${WWWGROUP:-1000}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            SEED_ON_BOOT: "1"
            SEED_CLASSES: "Database\\Seeders\\DatabaseSeeder"
        volumes:
            - '.:/var/www/html'
            - './docker/php/zz-listen.conf:/etc/php/8.2/fpm/pool.d/zz-listen.conf:ro'
        networks:
            - sail
        depends_on:
            - mysql

    nginx:
      image: nginx:stable-alpine
      depends_on:
        - laravel.test
      ports:
        - '80:80'
      volumes:
        - '.:/var/www/html'
        - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      networks:
        - sail

    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      depends_on:
        - mysql
      environment:
        PMA_HOST: mysql
        PMA_USER: '${DB_USERNAME}'
        PMA_PASSWORD: '${DB_PASSWORD}'
        UPLOAD_LIMIT: 256M
      ports:
        - '8081:80'
      networks:
        - sail

    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_EXTRA_OPTIONS: '${MYSQL_EXTRA_OPTIONS}'
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
